spring:
  datasource:
    url: jdbc:mysql://111.231.237.220/buy_ticket?characterEncoding=UTF8&serverTimezone=CTT
    username: root
    password: skittles
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/