spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buy_ticket?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/