spring:
  datasource:
    url: jdbc:mysql://111.231.237.220/buy_ticket?characterEncoding=UTF8&serverTimezone=CTT
    username: root
    password: skittles
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/



